merge upstream

diff --git a/.github/workflows/build-ready/action.yml b/.github/workflows/build-ready/action.yml
--- a/.github/workflows/build-ready/action.yml
+++ b/.github/workflows/build-ready/action.yml
@@ -9,7 +9,7 @@ runs:
           cd $GITHUB_WORKSPACE
           git clone --recursive "${{ env.KERNEL_SOURCE }}" -b "${{ env.KERNEL_BRANCH }}" device_kernel --depth=1
 
-          # Get KernelSU Version and Kernel Version
+          # Get Kernel Version
 
           KERNEL_VERSION=$(head -n 3 $GITHUB_WORKSPACE/device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')
           echo "KERNEL_VERSION=$(head -n 3 device_kernel/Makefile | grep -E 'VERSION|PATCHLEVEL' | awk '{print $3}' | paste -sd '.')" >> $GITHUB_ENV
@@ -115,29 +115,26 @@ runs:
                 KERNELSU_NAME="SukiSU-Ultra"
                 KERNELSU_ORIGIN_BRANCH="main"
                 if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
-                    KERNELSU_BRANCH="susfs-main"
+                    KERNELSU_BRANCH="builtin"
                 else
-                    KERNELSU_BRANCH="susfs-main"
+                    KERNELSU_BRANCH="builtin"
                 fi
             elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]]; then
                 KERNELSU_AUTHOR="KernelSU-Next"
                 KERNELSU_NAME="KernelSU-Next"
-                KERNELSU_ORIGIN_BRANCH="next"
+                KERNELSU_ORIGIN_BRANCH="legacy"
                 if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
-                    KERNELSU_BRANCH="next-susfs-a14-6.1-dev"
+                    echo "${{ env.KERNELSU_AUTO_FORK }} doesn't support SuSFS! "
+                    false
                 else
-                    KERNELSU_BRANCH="next"
+                    KERNELSU_BRANCH="legacy"
                 fi
             elif [[ "${{ env.KERNELSU_AUTO_FORK }}" == "wild" ]]; then
                 KERNELSU_AUTHOR="WildKernels"
                 KERNELSU_NAME="Wild_KSU"
                 KERNELSU_ORIGIN_BRANCH="wild"
                 if [[ "${{ env.SUSFS_ENABLE }}" == "true" ]]; then
-                    if [[ "${{ env.SUSFS_UPDATE }}" == "true" ]]; then
-                        KERNELSU_BRANCH="susfs"
-                    else
-                        KERNELSU_BRANCH="susfs-legacy"
-                    fi
+                    KERNELSU_BRANCH="susfs"
                 else
                     KERNELSU_BRANCH="wild"
                 fi
@@ -202,50 +199,8 @@ runs:
 
           # Core
           if [[ ${{ env.KERNELSU_AUTO_GET }} == "true" ]]; then
-
-            if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ] && [[ "${{ env.BUILD_DEBUGGER }}" == "false" ]]; then
-                if [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]]; then
-                    if grep -q "struct list_head task_alloc" "include/linux/lsm_hooks.h"; then
-                        echo "Your device supported the Manual SU function provided by SukiSU-Ultra!"
-                        echo "CONFIG_KSU_MANUAL_SU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-                    else
-                        echo ">>>Warning!<<<"
-                        echo "Your device cannot support the Manual SU function provided by SukiSU-Ultra!"
-                        echo "You can still compile it, but if you want to get Manual SU functionality, you need to port the task_alloc related functionality."
-                        echo ">>>>>>><<<<<<<"
-                        echo "CONFIG_KSU_MANUAL_SU=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-                    fi
-                fi
-            elif [[ "${{ env.BUILD_DEBUGGER }}" == "true" ]]; then
-                echo ">>>Warning!<<<"
-                echo "Kernel defects are also not blocked because the debugger feature is enabled."
-                echo ">>>>>>><<<<<<<"
-                echo "CONFIG_KSU_MANUAL_SU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            fi
-
             KERNELSU_AUTO
           else
-
-            if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ] && [[ "${{ env.BUILD_DEBUGGER }}" == "false" ]]; then
-                if [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]]; then
-                    if grep -q "struct list_head task_alloc" "include/linux/lsm_hooks.h"; then
-                        echo "Your device supported the Manual SU function provided by SukiSU-Ultra!"
-                        echo "CONFIG_KSU_MANUAL_SU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-                    else
-                        echo ">>>Warning!<<<"
-                        echo "Your device cannot support the Manual SU function provided by SukiSU-Ultra!"
-                        echo "You can still compile it, but if you want to get Manual SU functionality, you need to port the task_alloc related functionality."
-                        echo ">>>>>>><<<<<<<"
-                        echo "CONFIG_KSU_MANUAL_SU=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-                    fi
-                fi
-            elif [[ "${{ env.BUILD_DEBUGGER }}" == "true" ]]; then
-                echo ">>>Warning!<<<"
-                echo "Kernel defects are also not blocked because the debugger feature is enabled."
-                echo ">>>>>>><<<<<<<"
-                echo "CONFIG_KSU_MANUAL_SU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            fi
-
             KERNELSU_MANUAL
           fi
           echo "KERNELSU_METHOD=${{ env.KERNELSU_METHOD }}" >> $GITHUB_ENV
@@ -267,26 +222,36 @@ runs:
 
           if [[ -d "${{ env.KERNELSU_NAME }}/kernel/kpm" ]]; then
             if [ -f "include/linux/set_memory.h" ]; then
+
                 echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
                 ${{ env.CURLX }} "${{ env.KPM_PATCH_SOURCE }}" patch
                 chmod a+x patch
-                echo "Set KPM successfully !"
+                echo "[+]Set KPM successfully !"
+            elif [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
+
+                cp /tmp/Patches/Patch/set_memory_to_49_and_low.patch ./
+                patch -p1 < set_memory_to_49_and_low.patch || true
+                echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
+                ${{ env.CURLX }} "${{ env.KPM_PATCH_SOURCE }}" patch
+                chmod a+x patch
+                echo "[+]Patch set_memory successfully !"
+                echo "[-]If have patch error (.rej), manual fixed it."
             else
-                if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 10 ]; then
-                    cp /tmp/Patches/Patch/set_memory_to_49_and_low.patch ./
-                    patch -p1 < set_memory_to_49_and_low.patch || true
-                    echo "CONFIG_KPM=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-                    ${{ env.CURLX }} "${{ env.KPM_PATCH_SOURCE }}" patch
-                    chmod a+x patch
-                    echo "Patch set_memory successfully !"
-                    echo "If have patch error (.rej), manual fixed it."
-                else
-                    echo "Your kernel cannot support KPM function."
-                    false
-                fi
+
+                echo "===================Error==================="
+                echo "=                                         ="
+                echo "=Your kernel cannot support KPM function. ="
+                echo "=                                         ="
+                echo "==========================================="
+                false
             fi
           else
-            echo "KernelSU cannot support KPM !"
+
+            echo "=============Error============="
+            echo "=                             ="
+            echo "=KernelSU cannot support KPM !="
+            echo "=                             ="
+            echo "==============================="
             false
           fi
 
@@ -298,46 +263,13 @@ runs:
           # Neccssary
           echo "CONFIG_KSU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
           echo "# CONFIG_KPROBES is not set" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+          echo "CONFIG_HAVE_SYSCALL_TRACEPOINTS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
 
           # Fork
-          if [[ "${{ env.KERNELSU_SOURCE }}" == *rsuntk* ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "rsuntk" ]]; then
-            if [[ ${{ env.SUSFS_ENABLE }} == "true" ]] && [[ ${{ env.SUSFS_UPDATE }} == "true" ]]; then
-                echo "CONFIG_KSU_MANUAL_HOOK=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            else
+          if [[ "${{ env.KERNELSU_SOURCE }}" == *rsuntk* ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *next* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "rsuntk" ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]]; then
+            if [[ ${{ env.SUSFS_ENABLE }} != "true" ]]; then
+
                 echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            fi
-          fi
-
-          if [[ "${{ env.KERNELSU_SOURCE }}" == *next* ]] || [[ "${{ env.KERNELSU_SOURCE }}" == *wild* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "wild" ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "next" ]]; then
-
-            if grep -q "CONFIG_OVERLAY_FS" "./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}"; then
-                echo "Detected overlayfs, skipped."
-            else
-                echo "==============================================================Warning=============================================================="
-                echo "=                                 Your device defconfig does not have overlayfs enabled by default                                ="
-                echo "=                                                     it will be stopped next                                                     ="
-                echo "=                                  This will most likely cause your device to generate bootloop !                                 ="
-                echo "=It is therefore recommended that you replace the KernelSU Fork with a KernelSU Fork that does not require the Overlay FS feature.="
-                echo "=                                                                                                                                 ="
-                echo "=                                      KernelSU Fork currently known to require Overlay FS :                                      ="
-                echo "=                                           KernelSU Next, Wild KSU, KernelSU Official.                                           ="
-                echo "==================================================================================================================================="
-                echo "=                                    If you definitely need to bring Overlay FS to the device,                                    ="
-                echo "=                                then you need to place the following code in Extra Kernel Options                                ="
-                echo "=                                                                                                                                 ="
-                echo '=                  echo "CONFIG_OVERLAY_FS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}                  ='
-                echo "=                                                                                                                                 ="
-                echo "=             ,and just remove the false code from the corresponding area in .github/workflows/build-ready/action.yml             ="
-                echo "==================================================================================================================================="
-                false # Remove it to force build without Overlay fs
-            fi
-
-            echo "CONFIG_KSU_KPROBES_HOOK=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-
-            if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 2 ]; then
-                echo "CONFIG_KSU_LSM_SECURITY_HOOKS=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            else
-                echo "CONFIG_KSU_LSM_SECURITY_HOOKS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
             fi
           fi
 
@@ -352,22 +284,17 @@ runs:
           fi
 
           if [[ "${{ env.KERNELSU_SOURCE }}" == *SukiSU* ]] || [[ "${{ env.KERNELSU_AUTO_FORK }}" == "sukisu" ]]; then
-            if [[ "${{ env.HOOK_METHOD }}" == "tracepoint" ]]; then
-                echo "CONFIG_KSU_TRACEPOINT_HOOK=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
-                echo "Enabled tracepoint."
-            fi
+            echo "CONFIG_KSU_MANUAL_SU=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
 
             if [[ "${{ env.KPM_ENABLE }}" == "true" ]]; then
-                echo "CONFIG_DEBUG_KERNEL=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-                echo "CONFIG_KALLSYMS=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
                 echo "CONFIG_KALLSYMS_ALL=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
-            fi
-
-            if [ "${{ env.FIRST_VERSION }}" -lt 5 ] && [ "${{ env.SECOND_VERSION }}" -lt 5 ]; then
-                echo "CONFIG_KSU_THRONE_TRACKER_LEGACY=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
             fi
 
             if [[ "${{ env.SUSFS_ENABLE }}" != true ]]; then
                 echo "CONFIG_KSU_SUSFS=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+
+            elif [[ "${{ env.SUSFS_ENABLE }}" == true ]]; then
+                echo "CONFIG_KSU_MANUAL_HOOK=n" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
+                echo "CONFIG_KSU_NONE_HOOK=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}
             fi
           fi
