Merge upstream

diff --git a/.github/workflows/patch-no-kprobe/action.yml b/.github/workflows/patch-no-kprobe/action.yml
--- a/.github/workflows/patch-no-kprobe/action.yml
+++ b/.github/workflows/patch-no-kprobe/action.yml
@@ -50,42 +50,16 @@ runs:
           if grep -q "can_umount" "fs/namespace.c" && grep -q "ksu_init" "fs/exec.c"; then
             echo "Your kernel source code appears to have been manually patched, so this step is skipped."
 
-          # Check normal hook
-          elif [[ ${{ env.HOOK_METHOD }} == "normal" ]]; then
-            if [[ ${{ env.FIRST_VERSION }} -le 3 ]] && [[ ${{ env.SECOND_VERSION }} -le 10 ]]; then
-                echo "kernel ${{ env.KERNEL_VERSION }} doesn't support normal hook."
-                false
-            fi
-            cp /tmp/Patches/normal_hook_patches.sh ./
-            cp /tmp/Patches/backport_patches_early.sh ./
+          # Detect SuSFS is used to enable the SuSFS inline hook
+          elif [[ ${{ env.SUSFS_ENABLE }} == "true" ]] && [[ ${{ env.SUSFS_UPDATE }} == "true" ]] && ! grep -q "AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT" "drivers/kernelsu/Kconfig"; then
+            # Core
+            cp /tmp/Patches/susfs_inline_hook_patches.sh ./
+            bash susfs_inline_hook_patches.sh ./
 
-            bash normal_hook_patches.sh ./
-            bash backport_patches_early.sh
+            echo "executed SuSFS inline hook successfully."
 
-            echo "executed normal hook and backport patch successfully."
-
-          # Check syscall hook
-          elif [[ ${{ env.HOOK_METHOD }} == "syscall" ]]; then
-            if [[ "${{ env.HOOK_OLDER }}" == "true" ]]; then
-                cp /tmp/Patches/syscall_hook_patches_older.sh ./
-                bash syscall_hook_patches_older.sh ./
-
-                echo "executed syscall hook older successfully."
-            else
-                cp /tmp/Patches/syscall_hook_patches.sh ./
-                bash syscall_hook_patches.sh ./
-
-                echo "executed syscall hook successfully."
-            fi
-
-            if [[ ${{ env.FIRST_VERSION }} -le 3 ]] && [[ ${{ env.SECOND_VERSION }} -le 10 ]]; then
-                cp /tmp/Patches/backport_patches_early.sh ./
-                bash backport_patches_early.sh
-
-                echo "kernel ${{ env.KERNEL_VERSION }} doesn't kernel_write and kernel_read, so only executed backport patch older."
-            elif [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
+            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
                 cp /tmp/Patches/backport_patches.sh ./
-                cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_to_ksu.patch ./
 
                 bash backport_patches.sh
                 if grep -q "kernel_read" "fs/read_write.c"; then
@@ -95,7 +69,68 @@ runs:
                     echo ">                                           <"
                     echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
                 else
-                    patch -p1 < backport_kernel_read_and_kernel_write_to_ksu.patch || true
+                    if [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true
+                    else
+                        echo "Could not support ARMV7A kernel(Kernel Version < 3.18)"
+                        false
+                    fi
+                    REJ_FOUND
+                fi
+
+                echo "executed backport patch (contain kernel_read and kernel_write patch) successfully."
+            else
+                cp /tmp/Patches/backport_patches.sh ./
+                bash backport_patches.sh
+
+                echo "executed backport patch successfully."
+            fi
+
+          # Check syscall hook
+          elif [[ ${{ env.HOOK_METHOD }} == "syscall" ]]; then
+            # Core
+            cp /tmp/Patches/syscall_hook_patches.sh ./
+            bash syscall_hook_patches.sh ./
+
+            echo "executed syscall hook successfully."
+
+            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
+                cp /tmp/Patches/backport_patches.sh ./
+
+                bash backport_patches.sh
+                if grep -q "kernel_read" "fs/read_write.c"; then
+                    echo ">>>>>>>>>>>>>>>Backport Patch<<<<<<<<<<<<<<<<"
+                    echo ">                                           <"
+                    echo "Your kernel is already backported, skipping"
+                    echo ">                                           <"
+                    echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
+                else
+                    if [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true
+                    else
+                        echo "Could not support ARMV7A kernel(Kernel Version < 3.18)"
+                        false
+                    fi
                     REJ_FOUND
                 fi
 
@@ -120,22 +155,44 @@ runs:
                 echo "================================================================================="
                 false
             fi
+
+            # Core
             cp /tmp/Patches/tracepoint_hook_patches.sh ./
             bash tracepoint_hook_patches.sh ./
 
             echo "executed tracepoint hook successfully."
 
-            if [[ ${{ env.FIRST_VERSION }} -le 3 ]] && [[ ${{ env.SECOND_VERSION }} -le 10 ]]; then
-                cp /tmp/Patches/backport_patches_early.sh ./
-                bash backport_patches_early.sh
-
-                echo "kernel ${{ env.KERNEL_VERSION }} doesn't patch kernel_write and kernel_read, so only executed backport patch older."
-            elif [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
+            if [[ ${{ env.FIRST_VERSION }} -le 4 ]] && [[ ${{ env.SECOND_VERSION }} -le 9 ]]; then
                 cp /tmp/Patches/backport_patches.sh ./
-                cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_to_ksu.patch ./
 
                 bash backport_patches.sh
-                patch -p1 < backport_kernel_read_and_kernel_write_to_ksu.patch || true
+
+                bash backport_patches.sh
+                if grep -q "kernel_read" "fs/read_write.c"; then
+                    echo ">>>>>>>>>>>>>>>Backport Patch<<<<<<<<<<<<<<<<"
+                    echo ">                                           <"
+                    echo "Your kernel is already backported, skipping"
+                    echo ">                                           <"
+                    echo ">>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<"
+                else
+                    if [[ ${{ env.FIRST_VERSION }} == 3 ]] && [[ ${{ env.SECOND_VERSION }} == 18 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_3.18.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_3.18.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 4 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.4.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.4.patch || true
+                    elif [[ ${{ env.FIRST_VERSION }} == 4 ]] && [[ ${{ env.SECOND_VERSION }} == 9 ]]; then
+                        cp /tmp/Patches/Patch/backport_kernel_read_and_kernel_write_4.9.patch ./
+
+                        patch -p1 < backport_kernel_read_and_kernel_write_4.9.patch || true
+                    else
+                        echo "Could not support ARMV7A kernel(Kernel Version < 3.18)"
+                        false
+                    fi
+                    REJ_FOUND
+                fi
 
                 echo "executed backport patch (contain kernel_read and kernel_write patch) successfully."
             else
